all:
	coffee -c -o ../scripts tower_login.ext.coffee
	coffee -c -o ../scripts bbs.ext.coffee
	coffee -c -o ../scripts bugzilla.ext.coffee
	coffee -c -o ../scripts main.coffee
	coffee -c -o ../scripts hacking_day.coffee
	coffee -c -o ../pages background.coffee
	coffee -c -o ../pages/js popup.coffee
