all:
	coffee -cj ../scripts/bbs.ext.js bbs.ext.coffee
	coffee -cj ../scripts/hacking_day.js hacking_day.coffee
	coffee -cj ../scripts/main.js main.coffee
	coffee -cj ../scripts/bugzilla.ext.js bugzilla.ext.coffee
	coffee -cj ../scripts/tower_login.ext.js tower_login.ext.coffee
	coffee -cj ../pages/background.js background.coffee
	coffee -cj ../pages/js/popup.js popup.coffee
