// Generated by CoffeeScript 2.1.1
(function() {
  $("#loginForm").modal();

  $("#loginForm").submit(function() {
    $.ajax({
      type: 'POST',
      url: "https://bugzilla.deepin.io/jsonrpc.cgi",
      contentType: "application/json-rpc; charset=utf-8",
      dataType: 'json',
      data: JSON.stringify({
        method: "User.login",
        version: "1.1",
        params: [
          {
            login: $("#username").val(),
            password: $("#password").val()
          }
        ]
      }),
      success: function(data) {
        var ref;
        if (((ref = data.result) != null ? ref.token : void 0) != null) {
          chrome.cookies.set({
            name: "bugzilla_token",
            url: "https://tower.im",
            value: data.result.token,
            expirationDate: new Date().getTime() / 1000 + 2592000
          });
          return chrome.tabs.getCurrent(function(tab) {
            return chrome.tabs.remove(tab.id);
          });
        } else {
          return $("#error").html("<span>Login failed</span>");
        }
      },
      error: function() {
        return $("#error").html("<span>Login failed</span>");
      }
    });
    return false;
  });

}).call(this);
