// Generated by CoffeeScript 1.9.3
(function() {
  var $tokenMeta, d, port;

  port = chrome.runtime.connect({
    name: "dataconnect"
  });

  port.onMessage.addListener(function(msg) {
    switch (msg.type) {
      case "bugz_store_tower_token_result":
        return console.log("nothing need to be done, tmp");
    }
  });

  $tokenMeta = $("meta[name=Tower-Token]");

  if ($tokenMeta) {
    d = setInterval(function() {
      var con, expires, items, token;
      con = $tokenMeta.attr("content");
      if (con) {
        items = con.split(";");
        token = items[0];
        expires = items[1];
        port.postMessage({
          type: "bugz_store_tower_token",
          token: token,
          expires: expires
        });
        return window.clearInterval(d);
      }
    }, 500);
  }

}).call(this);
